macro(fx3_show_config)
    message(STATUS "")
    message(STATUS "${PROJECT_NAME} version: ${PROJECT_VERSION}")
    message(STATUS "  CXX COMPILER: ${CMAKE_CXX_COMPILER_ID}")
    message(STATUS "  C COMPILER: ${CMAKE_C_COMPILER_ID}")
    message(STATUS "  C COMPILER VERSION: ${CMAKE_C_COMPILER_VERSION}")
    message(STATUS "  CXX COMPILER VERSION: ${CMAKE_CXX_COMPILER_VERSION}")
    message(STATUS "  Installation target path: ${CMAKE_INSTALL_PREFIX}")
    if(CMAKE_TOOLCHAIN_FILE)
        message(STATUS "  Use toolchain file: ${CMAKE_TOOLCHAIN_FILE}")
    endif()
    message(STATUS "  Build for OS type: ${CMAKE_SYSTEM_NAME}")
    message(STATUS "  Build for OS version: ${CMAKE_SYSTEM_VERSION}")
    message(STATUS "  Build for CPU type: ${CMAKE_SYSTEM_PROCESSOR}")
    message(STATUS "  Build type: ${CMAKE_BUILD_TYPE}")

    string(TOUPPER "${CMAKE_BUILD_TYPE}" BUILD_TYPE)
    message(STATUS "  Build with cxx flags: ${CMAKE_CXX_FLAGS_${BUILD_TYPE}} ${CMAKE_CXX_FLAGS}")
    message(STATUS "  Build with c flags: ${CMAKE_C_FLAGS_${BUILD_TYPE}} ${CMAKE_C_FLAGS}")

    # FX3 specific configuration options
    message(STATUS "  Standard C Lib: ${ENABLE_STDC}")
    message(STATUS "  Standard C++ Lib: ${ENABLE_STDCXX}")
    message(STATUS "  Pedantic: ${ENABLE_PEDANTIC}")
    message(STATUS "  Werror: ${ENABLE_WERROR}")
    message(STATUS "  Build demo_c: ${BUILD_DEMO_C}")
    message(STATUS "  Build demo_cpp: ${BUILD_DEMO_CPP}")

    if(CMAKE_OBJCOPY)
        message(STATUS "  OBJCOPY: ${CMAKE_OBJCOPY}")
    else()
        message(STATUS "  OBJCOPY not set")
    endif()

    if(CMAKE_STRIP)
        message(STATUS "  STRIP: ${CMAKE_STRIP}")
    else()
        message(STATUS "  STRIP not set")
    endif()

    message(STATUS "")
endmacro()
